module.exports = {
  apps: [
    {
      name: 'auth-service',
      script: 'bun',
      args: 'src/index.ts',
      cwd: './services/auth',
      env: {
        NODE_ENV: 'development',
        PORT: 3001,
        HOST: '0.0.0.0',
        LOG_LEVEL: 'info',
      },
      watch: ['src'],
      ignore_watch: ['node_modules', 'dist', 'data'],
    },
    {
      name: 'data-service',
      script: 'bun',
      args: 'src/index.ts',
      cwd: './services/data',
      env: {
        NODE_ENV: 'development',
        PORT: 3002,
        HOST: '0.0.0.0',
        LOG_LEVEL: 'info',
      },
      watch: ['src'],
      ignore_watch: ['node_modules', 'dist', 'data'],
    },
    {
      name: 'processing-service',
      script: 'bun',
      args: 'src/index.ts',
      cwd: './services/processing',
      env: {
        NODE_ENV: 'development',
        PORT: 3003,
        HOST: '0.0.0.0',
        LOG_LEVEL: 'info',
      },
      watch: ['src'],
      ignore_watch: ['node_modules', 'dist', 'data'],
    },
    {
      name: 'integration-service',
      script: 'bun',
      args: 'src/index.ts',
      cwd: './services/integration',
      env: {
        NODE_ENV: 'development',
        PORT: 3004,
        HOST: '0.0.0.0',
        LOG_LEVEL: 'info',
        REDIS_DB: '1',
      },
      watch: ['src'],
      ignore_watch: ['node_modules', 'dist', 'data'],
    },
    {
      name: 'notification-service',
      script: 'bun',
      args: 'src/index.ts',
      cwd: './services/notification',
      env: {
        NODE_ENV: 'development',
        PORT: 3005,
        HOST: '0.0.0.0',
        LOG_LEVEL: 'info',
        REDIS_DB: '2',
        EMAIL_PROVIDER: 'smtp',
        SMS_PROVIDER: 'twilio',
        PUSH_PROVIDER: 'fcm',
      },
      watch: ['src'],
      ignore_watch: ['node_modules', 'dist', 'data'],
    },
  ],
};